services:
  - type: web
    name: zikr-tracker
    runtime: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: zikr_tracker
      - key: NODE_VERSION
        value: 20
